string-machine: Add missing libGL
Cairo no longer propagates libGL. The DPF submodule needs this:

src/pugl/pugl.h:39:14: fatal error: GL/gl.h: No such file or directory
   39 | #    include <GL/gl.h>
      |              ^~~~~~~~~
compilation terminated.