celluloid: Add missing libGL
Cairo no longer propagates libGL. I am looking at epoxy.pc and this is
in `Requires.private`. Hopefully this means fixing in celluloid can be fine.

/nix/store/xxx-libepoxy-1.5.10-dev/include/epoxy/egl_generated.h:11:10:
fatal error: EGL/eglplatform.h: No such file or directory
   11 | #include "EGL/eglplatform.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.